<a href="https://colab.research.google.com/github/hsi88/B-211/blob/main/b211_homwork2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np  

In [ ]:
#question 1
a = np.array ([[ 10, 1, 3], [ 3, 5, 12], [ 7, 13, 5]])
np.all(a != 5)



False

In [ ]:
b =np.array ([5, 3, 8, 7, 10]) 
b =np.asfarray(b)
b

array([ 5.,  3.,  8.,  7., 10.])

- question 3, Write a NumPy program to create a random 2d array 10X10 with 1000
elements and compute the mean and standard deviation of the array
elements

In [ ]:
c = np.random.rand(10,10)
print('mean =', c.mean())
print( 'std =' , c.std())

mean = 0.5034680713575117
std = 0.2891900400549789


question 4 Write a NumPy program to calculate cumulative product of the elements
along each row and each column for the following array:
([[ 0, 1, 3],
 [ 3, 7, 12],
 [ 6, 13, 21]]

In [ ]:
d = np.array([[ 0, 1, 3], [ 3, 7, 12], [ 6, 13, 21]])
d.cumsum(axis=1) # cumulataive row 


array([[ 0,  1,  4],
       [ 3, 10, 22],
       [ 6, 19, 40]])

In [ ]:
d.cumsum(axis=0) #cumulative column


array([[ 0,  1,  3],
       [ 3,  8, 15],
       [ 9, 21, 36]])

question 5.   Write a NumPy program to calculate the difference between neighboring
elements, element-wise of the following 1d array.
[10, 30, 50, 70, 100,80]

In [ ]:
e = np.array([10, 30, 50, 70, 100,80])
print("eighboring elements, element-wise of the said array.")
print(np.diff(e))

eighboring elements, element-wise of the said array.
[ 20  20  20  30 -20]


question 6 Display the names of the months between 2017 and 2018

In [ ]:
print(np.arange('2017-01','2018-01', dtype='datetime64[M]'))

['2017-01' '2017-02' '2017-03' '2017-04' '2017-05' '2017-06' '2017-07'
 '2017-08' '2017-09' '2017-10' '2017-11' '2017-12']


question 7

Write a NumPy program to explore iris dataset and do the following:
• Print the shape of the dataset.
• Print the column names (features) up to the last column.
• Print the last column name.
• Check the type of all column in the dataset, excluding the last column.
• Check the type of the last column in the dataset.
• Check the shape of the dataset, excluding the last column.
• Check the shape of the last column in the dataset.
• Print the value of the 2nd column for the 25th sample/data point in the
dataset.
• Print the value of the last column for the 99th sample/data point in the
datasetq

In [ ]:
# • Print the shape of the dataset. 
file = open('/iris.data.csv')
h= np.genfromtxt(file, delimiter=",") 
h.shape

(151, 5)

In [ ]:
#Print the column names (features) up to the last column.
file = open('/iris.data.csv')
data = np.genfromtxt(file, delimiter=",", names=True)
print(data.dtype.names)
# 'names' read the headline


('sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class')


In [ ]:
# Print the last column name. • 
print(data.dtype.names[-1])

class


In [ ]:
#• Check the type of all column in the dataset, excluding the last column.
file = open('/iris.data.csv')
dt = np.genfromtxt(file, delimiter=",", names=True)
print(dt.dtype)


[('sepal_length', '<f8'), ('sepal_width', '<f8'), ('petal_length', '<f8'), ('petal_width', '<f8'), ('class', '<f8')]


In [ ]:
# Check the type of the last column in the dataset. • 
file = open('/iris.data.csv')
dt = np.genfromtxt(file, delimiter=",", names=True)
print(dt.dtype[-1])

float64


In [ ]:
# Check the shape of the dataset, excluding the last column. 
file = open('/iris.data.csv')
dt = np.genfromtxt(file, delimiter=",", usecols=(0,1,2,3))
print(dt.shape)

# This will give the number of columns is 2-d array 


(151, 4)


In [ ]:
# Check the shape of the last column in the dataset

file = open('/iris.data.csv')
dt = np.genfromtxt(file, delimiter=",", usecols=(4))
print(dt.shape)


(151,)


In [ ]:
# Print the value of the 2nd column for the 25th sample/data point in the dataset

file = open('/iris.data.csv')
dt = np.genfromtxt(file, delimiter=",", dtype=None)
print(dt[25])
              
                

[b'4.8' b'3.4' b'1.9' b'0.2' b'Iris-setosa']


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


In [ ]:
# Print the value of the last column for the 99th sample/data point in the

file = open('/iris.data.csv')
dt = np.genfromtxt(file, delimiter=",", dtype= None)
print(dt[99,-1])

# dtype = none,  read all dtype 

b'Iris-versicolor'


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.
