<a href="https://colab.research.google.com/github/hsi88/B-211/blob/main/B211_homework_5__scikit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Get the shape of dataset and print the number of samples and the number columns in this dataset.
import pandas as pd
from sklearn import datasets
url = '/diabetes.csv'
da = pd.read_csv('/diabetes.csv')
da

Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [ ]:
# Get the number of features and their names. 


da1 = da.drop('Outcome', axis=1)
name = da1.columns.to_list()
print(name)
len(name)
print('number of features is' , len(name))


['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']
number of features is 8


In [ ]:
#Get the shape of the target variable column
dtarget = da['Outcome']
dtarget.shape

(768,)

In [ ]:
##Using scikit-learn, develop a machine learning classifier (support vector or k-nearest
#neighbors or random forest or decision tree classifiers) that can be fit on 80 % of this
#dataset for learning or training and predict the class of patient either diabetes or not on
#the remaining 20 % of this dataset.
from sklearn import svm

clf = svm.SVC(gamma=0.001, C=100) 
clf.fit(da1[:-145], dtarget[:-145,])
clf.predict(da1[-145:])


array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0])

In [ ]:
# Test the performance of your classifier by reporting about the its accuracy, precision,
# recall and F1-score.
from sklearn import metrics
true = dtarget[-145:]
pred = clf.predict(da1[-145:])



In [ ]:
import numpy as np

dtarget[-145:] .to_numpy()

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [ ]:
pred

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0])

In [ ]:
from sklearn.metrics import accuracy_score
print('accuracy score TP+TN/(TP+FP+TN+FN) :', accuracy_score(true, pred))

accuracy score TP+TN/(TP+FP+TN+FN) : 0.6482758620689655


In [ ]:
print('precision score tp/tp+fp: ', metrics.precision_score(true, pred))


precision score tp/tp+fp:  0.5106382978723404


In [ ]:
print('recall socre. tp/tp+fn :', metrics.recall_score(true, pred))

recall socre. tp/tp+fn : 0.46153846153846156


In [ ]:
print('f1 score:', metrics.f1_score(true, pred)  )

f1 score: 0.48484848484848486


In [ ]:
#print the TP, TN, FP, FN measures from the confusion matrix of the classifier that you have
# developed.
from sklearn.metrics import confusion_matrix
tn, fp, fn, tp = confusion_matrix(true, pred).ravel()
print('tn, fp, fn, tp')
print(tn, fp, fn, tp)


tn, fp, fn, tp
70 23 28 24


#2- Explore the cpu-performance dataset available at

In [ ]:
#by loading its csv file and doing the following:
import numpy as np

import pandas as pd
cpu = pd.read_csv('/machine.data.csv')
cpu

adviser          32/60  125   256   6000  256.1  16  128  198  199
0    amdahl         470v/7   29  8000  32000     32   8   32  269  253
1    amdahl        470v/7a   29  8000  32000     32   8   32  220  253
2    amdahl        470v/7b   29  8000  32000     32   8   32  172  253
3    amdahl        470v/7c   29  8000  16000     32   8   16  132  132
4    amdahl         470v/b   26  8000  32000     64   8   32  318  290
..      ...            ...  ...   ...    ...    ...  ..  ...  ...  ...
203  sperry           80/8  124  1000   8000      0   1    8   42   37
204  sperry  90/80-model-3   98  1000   8000     32   2    8   46   50
205  sratus             32  125  2000   8000      0   2   14   52   41
206    wang         vs-100  480   512   8000     32   0    0   67   47
207    wang          vs-90  480  1000   4000      0   0    0   45   25

[208 rows x 10 columns]

In [ ]:
# Get the shape of the dataset excluding the target variable column.
cpudata = cpu.iloc[:,2:9]
cpudata.shape

# excluding the first and second columns beacuse they are string, can not be coverted to numeric 


(208, 7)

In [ ]:
cpudata
#cpudata['adviser'] = pd.to_numeric(cpudata['32/60']).astyple(int)
#cpudata.dtypes

125   256   6000  256.1  16  128  198
0     29  8000  32000     32   8   32  269
1     29  8000  32000     32   8   32  220
2     29  8000  32000     32   8   32  172
3     29  8000  16000     32   8   16  132
4     26  8000  32000     64   8   32  318
..   ...   ...    ...    ...  ..  ...  ...
203  124  1000   8000      0   1    8   42
204   98  1000   8000     32   2    8   46
205  125  2000   8000      0   2   14   52
206  480   512   8000     32   0    0   67
207  480  1000   4000      0   0    0   45

[208 rows x 7 columns]

In [ ]:
# Get the number of samples in this dataset
cpudata.info

<bound method DataFrame.info of      125   256   6000  256.1  16  128  198
0     29  8000  32000     32   8   32  269
1     29  8000  32000     32   8   32  220
2     29  8000  32000     32   8   32  172
3     29  8000  16000     32   8   16  132
4     26  8000  32000     64   8   32  318
..   ...   ...    ...    ...  ..  ...  ...
203  124  1000   8000      0   1    8   42
204   98  1000   8000     32   2    8   46
205  125  2000   8000      0   2   14   52
206  480   512   8000     32   0    0   67
207  480  1000   4000      0   0    0   45

[208 rows x 7 columns]>

In [ ]:
#Get the number of features and their names. 
cpudata.columns.to_list()

['32/60', '125', '256', '6000', '256.1', '16', '128', '198']

In [ ]:
# Get the shape of the target variable column
cputar = cpu.iloc[:,9]
cputar.infer_objects


<bound method NDFrame.infer_objects of 0      253
1      253
2      253
3      132
4      290
      ... 
203     37
204     50
205     41
206     47
207     25
Name: 199, Length: 208, dtype: int64>

In [ ]:
#using scikit-learn, develop a machine learning regression model (support vector for
#regression (SVR) or linear regression LR) that can be fit on 160 samples of this dataset for
#learning or training and predict the value of cpu-performance on the remaining samples
#of this dataset.

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(cpudata[:161], cputar[:161]) 
model.predict(cpudata[162:208])


array([ 65.42093003,  80.04189875,  74.98547797, 105.03230574,
       149.48669153, 202.28569979, 183.71781178,   2.88132603,
        11.75564542,  44.6770198 ,   7.05116063,  21.36306452,
        61.56010357,   6.13148071,   2.77257391,  15.63095582,
        39.30298341,  72.45881084, -11.29403886,  -5.61270276,
        16.69559556,  32.36047394,  48.28889992, 124.75894414,
        86.50171634, 106.21729331, 199.68494549, 209.80446822,
       276.61325557, 367.46928567,  57.85026428, 152.45882951,
       218.77366492, 298.86441126, 358.73345792, 704.34550997,
       815.89794431,  -4.11282999,  -0.90509388,  -1.33927666,
         2.33071834,  27.69574429,  32.4498591 ,  42.93682013,
        48.89247676,  27.48609477])

In [ ]:
from sklearn.metrics import mean_squared_error
y_true = cpudata.iloc[162:208, 6]
y_true.to_numpy()

array([  42,   46,   51,  116,  100,  140,  212,   25,   30,   41,   25,
         50,   50,   30,   32,   38,   60,  109,    6,   11,   22,   33,
         58,  130,   75,  113,  188,  173,  248,  405,   70,  114,  208,
        307,  397,  915, 1150,   12,   14,   18,   21,   42,   46,   52,
         67,   45])

In [ ]:
y_pred = model.predict(cpudata[162:208])
y_pred

array([ 65.42093003,  80.04189875,  74.98547797, 105.03230574,
       149.48669153, 202.28569979, 183.71781178,   2.88132603,
        11.75564542,  44.6770198 ,   7.05116063,  21.36306452,
        61.56010357,   6.13148071,   2.77257391,  15.63095582,
        39.30298341,  72.45881084, -11.29403886,  -5.61270276,
        16.69559556,  32.36047394,  48.28889992, 124.75894414,
        86.50171634, 106.21729331, 199.68494549, 209.80446822,
       276.61325557, 367.46928567,  57.85026428, 152.45882951,
       218.77366492, 298.86441126, 358.73345792, 704.34550997,
       815.89794431,  -4.11282999,  -0.90509388,  -1.33927666,
         2.33071834,  27.69574429,  32.4498591 ,  42.93682013,
        48.89247676,  27.48609477])

In [ ]:
print('mean sqaured error')
mean_squared_error(y_true, y_pred)

mean sqaured error


3946.410770264073

In [ ]:
 #from sklearn.metrics import mean_absolute_error
 from sklearn.metrics import mean_absolute_error
 print('mean absolute error')
 mean_absolute_error(y_true,y_pred)

mean absolute error


31.504059373618357